### PR TITLE
Update Verify

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by danielcweber** [comment]
@SimonCropp  Thanks for the initiative. Unfortunately, I can't update Verify beyond the current version. The older version would allow me to inherit from a base unit test class (in Base.cs) and inherit from there, allowing for different unit test environments (e.g. Provider1Tests.cs, Provider2Tests.cs). The name of the source file would be passed down, and the .verified files would just align. It's not possible anymore with a higher version as far as I can see. The setup is much simpler now, which is good, but it breaks things for this project. Is there actually a way to update that I missed?

**Comment by danielcweber** [comment]
@SimonCropp Just discovered that what I wrote previously doesn't account for the build to fail, but rather the nuget-push. So things might actually work with my inheritance scenario? Would be cool. Will investigate after my vacation. Thanks a lot!

**Comment by SimonCropp** [comment]
yeah the current version of verify doesnt require a base class. the previous verify base class inherited from xunitcontextbase, so i replaced your use of verifybase with xunitcontextbase. i could probably remove your need for a base class completely, but i figured this PR was a good first step

**Comment by SimonCropp** [comment]
disclaimer: i am the maintainer of Verify and xunitcontext

**Comment by danielcweber** [comment]
But would the current version allow for inherited unit test classes?

Example: https://github.com/ExRam/ExRam.Gremlinq/blob/main/ExRam.Gremlinq.Providers.CosmosDb.Tests/CosmosDbQuerySerializationTestBase.cs

It inherits all the test from the base class, but might have different output since the environment setup is different. Older versions of Verify would create "CosmosDbQuerySerializationTestBase.xyz.verified" files, newer versions would be ignorant to the file name of the derived class.

**Comment by SimonCropp** [comment]
> But would the current version allow for inherited unit test classes?

yep i handled all you inheritance cases

**Comment by SimonCropp** [comment]
if it makes it easier, we can abandon this PR, and I can look at add a cut down version of VerifyBase back in (without the dependency on xunit base).

FYI: the reason i removed VerifyBase was many people didnt like the requirement for a base class to use the API. unfortunately xunit does not make this scenario easy to implement.

**Comment by danielcweber** [comment]
I can see most of the magic happens [here](https://github.com/ExRam/ExRam.Gremlinq/pull/106/files#diff-e5aafd6e39aecdc8c4fa522cb4e746a1R43). It's awesome that it's possible. Thank you very much.

>if it makes it easier, we can abandon this PR, and I can look at add a cut down version of VerifyBase back in
I think it's perfectly fine as it is, as it seems to be the cleanest way.

Again thanks a lot!

**Comment by SimonCropp** [comment]
fyi Verify 6.15.0 re-adds VerifyBase

**Pull request merged**
