### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dli9431**
Added an Azure Cosmo DB config example to the end of the readme

### CODE REVIEW

**Comment by danielcweber** [comment]
Thanks for the idea, however, I'm trying to get these kind of examples into the new `dotnet new` templates and eventually into a proper website. Is there anything in your example that's missing from the respective CosmosDb template?

**Comment by dli9431** [comment]
When I generated the AspNet CosmosDb template it just had:

builder.Services
    .AddGremlinq(setup => setup
        .UseCosmosDb<Vertex, Edge>()
        .UseNewtonsoftJson())
    .AddControllers();
    
I think in the template it's supposed to get its configuration settings from the appsettings.json file but I use User secrets/Key vault in my project so the additional .Configure() call was needed (that part's also missing from the console version template). I appreciate what you're doing just thought an updated example config would help if people found themselves in that situation.

**Comment by danielcweber** [comment]
I am not sure I understand...is something missing from the templates that makes it unusable out of the box? I cannot see how your addition to the Readme shows anything related to Azure Key Vault.

**Comment by danielcweber** [comment]
I changed the branch structure in Gremlinq to only build from e.g. 12.x branches and deleted main, so this got automatically deleted. Please rebase your proposed changes to target the 12.x branch and file a new PR. Thanks a lot and sorry for the inconvenience.

**Pull request closed without merging**
