### PR TITLE
Add Update and Replace methods to support CRUD operations

### PR DESCRIPTION
**Pull request by SyntaxUnknown**
Continuation of PR #11 and requires the changes in #12.

This adds the query methods `UpdateV`, `UpdateE`, `ReplaceV`, and `ReplaceE`. It also updates `AddV` and `AddE` to support Ignored properties in the configuration.

### CODE REVIEW

**Comment by SyntaxUnknown** [comment]
Hmmm, it looks like my commit for PR #12 got included with this one. Let me know if we can still proceed or if this one needs to wait for the other.

**Comment by SyntaxUnknown** [comment]
I'm going to go ahead and close this one until PR #12 is completed because it's too confusing with the multiple commits.

**Comment by danielcweber** [comment]
Still interested in implementing this functionality? Have a look at the current master. Inspired by your 'metaData-storage' approach, I gave the graph models a major rework. Everything is more fluent, immutable, extensible straightforward now...at least that's what I was aiming for. This is gonna be a major verson bump, a preview could be released soon.

**Comment by SyntaxUnknown** [comment]
Yep! I've been busy working on other portions of our application right now, but I do plan on circling back and getting the Update/Replace code merged in soon. The update sounds exciting, so I'm looking forward to taking a look!

**Pull request closed without merging**
