### PR TITLE
Implemented a test for fantomly typed value object

### PR DESCRIPTION
**Pull request by xperiandri**
@danielcweber this test succeeds while using struct in production it fails

### CODE REVIEW

**Comment by danielcweber** [comment]
So...is this CI run supposed to fail or not?

**Comment by danielcweber** [comment]
@xperiandri  I have still no way of reproducing any kind of failure.

**Comment by xperiandri** [comment]
@danielcweber as I mentioned above CI will succeed because the test I implemented succeeds.
But, when I use this same code in production (talking to a database) it fails.
And I do not know what test to implement to reproduce that.
Can you help?

**Comment by xperiandri** [comment]
Deserializing generic struct fails on real database

**Comment by danielcweber** [comment]
> @danielcweber as I mentioned above CI will succeed because the test I implemented succeeds. But, when I use this same code in production (talking to a database) it fails. And I do not know what test to implement to reproduce that. Can you help?

@xperiandri If it cannot be shown to be a bug in Gremlinq, you can always book a [paid support](https://github.com/ExRam/ExRam.Gremlinq?tab=readme-ov-file#paid-support) session with me and we'll have a look at your setup.

**Comment by xperiandri** [comment]
If you can advise me where to write a test I can try myself first

**Comment by danielcweber** [comment]
Closing since I have no clue what the issue is here. If it persists, please write some reproduction code.

**Pull request closed without merging**
