### PR TITLE
For release/update vertex edge

### PR DESCRIPTION
**Pull request by SyntaxUnknown**
Here's my attempt at implementing an UpdateV and UpdateE pattern. Let me know what you think!

There are 3 ways to use it:

1. Using attributes to exclude properties for update. In this case, the properties Id, Type, and PartitionKey are not updated.
```
public abstract class Vertex : IVertex
{
    [ReadOnly]
    public object Id { get; set; }

    [ReadOnly]
    public string Type => GetType().Name;

    [ReadOnly]
    public string PartitionKey => $"{Type}_{Id}";

    public bool IsDeleted { get; set; }
}

// Usage
g.V(person.Id).UpdateV(person).First();

```

2. Supplying a list of properties to exclude in the Update method. Here, Name and RegistrationDate are excluded in this update.
```
g.V<Person>(person.Id)
    .UpdateV(person,
         ImmutableList<string>.Empty.AddRange(new[] { nameof(Person.Name), nameof(Person.RegistrationDate) }))
    .First();
```

3. Supplying a filter function to exclude in the Update method. This function to do any sort of work, but here I'm just going off the property name.
```
g.V<Person>(person.Id)
    .UpdateV(person, (property) => property == nameof(Person.Name) || property == nameof(Person.RegistrationDate))
    .First();
```

### CODE REVIEW

**Comment by danielcweber** [comment]
I unfortunately don't see either way working for Gremlinq at the moment. Generally, I wouldn't want to have multiple ways of achieving the same things, the maintenance costs ist just too high and the power of the different methods might diverge over time.

As for 1., as I said, I want to avoid any attribute based configuration. I don't see 2. either since it would require you to repeat the same exclusions everywhere you update a vertex/edge of a specific type. Same for 3.

I think configuration should rather happen at the model level, e.g.
`...model.Configure<Entity>(c => c.ReadOnly(e => e.Property))`.

**Comment by SyntaxUnknown** [comment]
Wow, that puts a lot responsibility on an external class to know intimate details about the workings of every entity in the system. I'm not sure I like that. Having that knowledge closest to the source of truth is much cleaner.

Most serialization libraries provide this attribute based approach for a reason.

I guess I'll have to either find a way to implement this logic externally to your library or just continue to use my forked version, unfortunately.

**Comment by danielcweber** [comment]
For me, the fluent-based-configuration approach is equally powerful as is the attribute-based. I see that you'd like to define it close to the POCOs, but again, what if there's no access to the POCOs?

Once you got a fluent configuration interface for these things, you can easily use this as an extension point for attribute based configuration. You'll just need something that will scan the attributes and call the corresponding methods on the model.

**Comment by danielcweber** [comment]
Just thinking...what if the existence of a private setter on a property was already an indicator to exclude the property in gremlin...after all, that is what makes a property read-only. Not any attribute.

**Comment by SyntaxUnknown** [comment]
That does seem like an ideal solution, but I'm not sure if the deserialization would work if the setters are private. I'll give it a shot and let you know.

I did try to address not owning the POCOs with the filter params which would allow the data store classes the ability to decide which properties to exclude at save time. I can remove that functionality and they'd just have to update properties individually instead of using UpdateV for that use case.

If the private setter path does not work, I like your idea about being able to extend the model approach to scan for the attribute, so I'll take a stab at implementing that. 

Thanks again for your help!

**Comment by danielcweber** [comment]
One more thing: I think the pattern `V(...id).UpdateV(entity)` should be reduced to `Replace(entity)`, where entity must have its id already set.

**Comment by SyntaxUnknown** [comment]
Do you want ReplaceV/ReplaceE or just one replace for both?

**Comment by danielcweber** [comment]
Interesting question. We have AddV and AddE, given that we theoretically could know from the model, we don't even need those and Add would do. So, do we need ReplaceV and ReplaceE? Whatever is easier for a first implementation I would say.

**Comment by SyntaxUnknown** [comment]
Switching from Update to Replace might cause some limitations, especially when dealing with edges.

For example, I was thinking the edge update would work as follows:
```
g.V(...id).OutE("worksFor").UpdateE(updatedEdge)
```
Would ReplaceE require me to find that edge's ID first and then update it? 

If we stick with UpdateV/UpdateE, it allows the user greater flexibility to get to the item they wish to update. What do you think?

**Comment by danielcweber** [comment]
I'll have to think about that.

Currently, I tend to have both ways: `Replace` will take an object where the id is set so one can go `g.Replace(updatedVertex)` and `Update` for `...OutE(...).Update(updatedEdge)`. Question is in the latter case, what to do when `updatedEdge` has an id set (because it's pretty much useless). Is it still intuitive to use?

**Comment by SyntaxUnknown** [comment]
I think it is. The the `Update` method would also allow for multiple updates in one call like `g.Replace(updatedVertex).OutE(...).Update(updatedEdge)`

So, are you ok going with the two methods `Replace` and `Update`?

**Comment by danielcweber** [comment]
Yes

**Comment by SyntaxUnknown** [comment]
Well, I went through and implemented `Update` where it could take a Vertex or Edge, but ran into a major problem. The method needs to return either an `IVertexGremlinQuery` or `IEdgeGremlinQuery` based on the type passed in. Since there is no real way to scope the parameters to 'Update' to be either a Vertex or Edge at compile time, I don't see a work around for this one.

I'm going to go ahead and run with `UpdateV`, `UpdateE`, `ReplaceV` and `ReplaceE`, unless you can think of something to work around the issue.

**Comment by SyntaxUnknown** [comment]
Here's another update for you. 

Changes:
1 - Removed the Attribute-based configuration.
2 - Removed extra methods I had in there for filtering out properties.
3 - Added fluent configuration for properties from the model. For example:
```
 g
    .WithLogger(_logger)
    .WithModel(GraphModel.Dynamic()
        .WithCamelcaseLabels()
        .WithCamelcaseProperties()
        .Configure(builder =>
            {
                builder.Element<Person>()
                    .ReadOnly(p => p.Id)
                    .Ignore(p => p.SomethingNotPersisted);
            }))
    .WithCosmosDbRemote(...);
```
`ReadOnly` is ignored during updates and `Ignore` is ignored during adds and updates.

4 - Implemented `UpdateV`, `UpdateE`, `ReplaceV`, `ReplaceE`

Again, let me know if you need me to change anything.

Thanks again!!

**Comment by danielcweber** [comment]
I will try to review it during the weekend/next week. Two things:

- I really think this should be two PRs. One for the fluent configuration, one for the update/replace, to simplify review.
- I haven't thoroughly looked at it, but make sure you don't introduce mutability. If you look closely, you will observe that all the queries and models are immutable, i.e. every new configuration yields a new model.
- Can you please rebase it on the current master to get rid of those automatic github merge commits.

Thanks a lot for your effort!

**Comment by SyntaxUnknown** [comment]
Ok, closing this one and breaking it up into two PRs.

**Pull request closed without merging**
