### PR TITLE
Implemented a test for fantomly typed value object

### PR DESCRIPTION
**Pull request by xperiandri**
@danielcweber this test succeds while using struct in production it fails

### CODE REVIEW

**Comment by xperiandri** [comment]
Where can more tests for value-objects serialization and deserialization can be written?

**Comment by danielcweber** [comment]
What is a fantomly typed value object?

**Comment by xperiandri** [comment]
So your implementation works if value object is a class but crashes if value object is a structure

**Comment by danielcweber** [comment]
I changed the branch structure in Gremlinq to only build from e.g. 12.x branches and deleted main, so this got automatically deleted. Please rebase your proposed changes to target the 12.x branch and file a new PR. Thanks a lot and sorry for the inconvenience.

**Pull request closed without merging**
